baseurl = "http://othello-lang.org/"
languageCode = "en-us"
title = "Othello"
theme = "alabaster"

[params]
        name = "Othello Lang"
        description = "Othello Programming Language"

        github_user = "swarthout"
        github_repo = "othello"
        github_banner = false

[params.sidebar]
        github_button = true

[params.footer]
        copyright = "[Scott Swarthout](https://github.com/swarthout)"


[[menu.docs]]
  name = "Language Basics"
  weight = 15
  identifier = "language-basics"
  url = "/language-basics/overview/"
